#sudo: enabled
#language: C
#dist: trusty
#os:
  #- linux
#compiler:
  #- gcc
  #- clang
#install:
  #- sudo apt-get install -y libglib2.0-dev libev-dev python3
#script:
  #- make tests



sudo: required
dist: trusty

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose up --build -d

script:
  - python3 tests/integration/main.py -afd

after_script:
  - docker-compose down
